markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: wjsaya
author: "wjsaya"
email: wjsaya@163.com
name: "wjsaya个人博客"
url: https://wjsaya.github.io
all_categories: [
["web", "Web建站","/posts/web.html"], 
["linuxops", "linux运维","/posts/linuxops.html"],
["python", "python","/posts/python.html"],
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: China/Beijing

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
